### PR TITLE
Ability to use different templates or CSS for iOS and Android added

### PR DESCRIPTION
**Pull request by Andrew8xx8**
It allows creating templates named as `page-name.[platform_name].xml` witch will be used on a specific platform.

Same thing about CSS. 

This feature is very useful in my case.

### CODE REVIEW

**Comment by enchev** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
@Andrew8xx8, can you please, sign the [CLA](http://www.nativescript.org/cla)?

**Comment by Andrew8xx8** [comment]
@ErjanGavalji done

**Comment by dtopuzov** [comment]
bot, run CI

**Comment by dtopuzov** [comment]
bot, run ci

**Comment by ErjanGavalji** [comment]
bot, run ci

**Comment by ErjanGavalji** [comment]
run ci

**Comment by ErjanGavalji** [comment]
test this please

**Comment by ErjanGavalji** [comment]
bot run ci now

**Comment by ligaz** [comment]
@ErjanGavalji This specific functionality should be easily unit testable. We need to figure out how to enable this for such cases.

**Comment by ligaz** [comment]
@Andrew8xx8 This functionality should already be working if you are using the CLI. [Here](https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/platform-service.ts#L381) is the relevant code that does the platform specific files transformation.

**Comment by vakrilov** [comment]
@Andrew8xx8 Thanks for the contribution! I have used your commits in another PR #205

**Pull request closed without merging**
